import { StyleSheet } from 'react-native';

export const PRIMARY_COLOR = '#088395';
export const ADMIN_DANGER_COLOR = '#EF4444';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F8FAFC' },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingTop: 10,
        paddingBottom: 10,
        elevation: 2,
    },
    headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#1E293B', marginLeft: 10 },
    imageContainer: { position: 'relative' },
    image: { width: '100%', height: 250, resizeMode: 'cover' },
    adminBadge: {
        position: 'absolute',
        top: 15,
        left: 15,
        backgroundColor: ADMIN_DANGER_COLOR,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        elevation: 5,
    },
    adminBadgeText: { color: '#FFF', fontWeight: 'bold', fontSize: 12, marginLeft: 5 },
    starBadge: {
        position: 'absolute',
        bottom: 30,
        right: 15,
        backgroundColor: 'rgba(0,0,0,0.7)',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 15,
    },
    starText: { color: '#FFD700', fontWeight: 'bold', marginLeft: 5 },
    content: { padding: 15, backgroundColor: '#FFF', borderTopLeftRadius: 25, borderTopRightRadius: 25, marginTop: -20 },
    adminInfoBox: {
        backgroundColor: '#FFF1F2',
        padding: 15,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#FECDD3',
    },
    adminBoxTitle: { fontWeight: 'bold', fontSize: 15, color: ADMIN_DANGER_COLOR, marginBottom: 10, textTransform: 'uppercase' },
    adminInfoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 4 },
    adminInfoLabel: { color: '#475569', fontSize: 14 },
    adminInfoValue: { color: '#1E293B', fontSize: 14, fontWeight: 'bold' },
    name: { fontSize: 22, fontWeight: 'bold', color: '#1E293B', marginBottom: 8, lineHeight: 30 },
    addressRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 15, paddingRight: 15 },
    addressText: { fontSize: 14, color: '#64748B', marginLeft: 6, lineHeight: 20, flex: 1 },
    priceContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
    priceLabel: { fontSize: 13, color: '#64748B', marginBottom: 2 },
    priceValue: { fontSize: 20, fontWeight: 'bold', color: PRIMARY_COLOR },
    highlightBox: { 
        backgroundColor: '#F1F5F9', 
        padding: 15, 
        borderRadius: 12, 
        marginBottom: 15,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center'
    },
    infoCol: { alignItems: 'center', flex: 1 },
    verticalDivider: { width: 1, height: 40, backgroundColor: '#CBD5E1', marginHorizontal: 15 },
    infoLabel: { fontSize: 13, color: '#64748B', marginTop: 4 },
    infoValue: { fontSize: 16, fontWeight: 'bold', color: '#1E293B', marginTop: 2 },
    amenitiesContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 15 },
    amenityChip: { backgroundColor: '#E2E8F0', height: 32 },
    amenityText: { fontSize: 13, color: '#334155' },
    accordion: { backgroundColor: '#F8FAFC', borderRadius: 10, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 10 },
    accordionTitle: { fontWeight: 'bold', color: '#1E293B' },
    accordionContent: { paddingHorizontal: 15, paddingBottom: 10 },
    divider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 20 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#1E293B', marginBottom: 15 },
});