import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F1F5F9',
    },
    header: {
        backgroundColor: '#088395',
        paddingTop: Platform.OS === 'ios' ? 60 : 45,
        paddingBottom: 25, 
        paddingHorizontal: 20,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        elevation: 5,
        shadowColor: '#088395',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        marginBottom: 15, 
    },
    headerTitle: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#ffffff',
        letterSpacing: 0.5,
    },
    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.85)',
        marginTop: 4,
    },
    listContent: {
        paddingHorizontal: 16,
        paddingBottom: 30,
    },
    card: {
        marginBottom: 16,
        borderRadius: 20, 
        backgroundColor: '#ffffff',
        borderWidth: 0, 
        elevation: 3, 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
    },
    rowBetween: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start', 
    },
    serviceName: {
        fontWeight: 'bold',
        color: '#1E293B',
        flex: 1,
        marginRight: 12,
        fontSize: 16,
        lineHeight: 24, 
    },
    statusChip: {
        height: 28,
        borderRadius: 8,
        paddingHorizontal: 4, 
        justifyContent: 'center',
        alignItems: 'center',
    },
    statusText: {
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1.2,
        textAlign: 'center',
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        marginBottom: 8,
    },
    dateText: {
        color: '#64748B',
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '500',
    },
    footerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 5,
    },
    totalAmountLabel: {
        color: '#64748B',
        fontSize: 14,
    },
    totalAmount: {
        color: '#088395', 
        fontWeight: '900', 
        fontSize: 18,
        letterSpacing: 0.5,
    }, 
    customerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        backgroundColor: '#F8FAFC', 
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 10,
    },
    customerName: {
        color: '#334155',
        fontSize: 13,
        fontWeight: 'bold',
        marginLeft: 6,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
    },
    emptyText: {
        color: '#94A3B8',
        fontSize: 16,
        marginTop: 12,
        fontWeight: '500',
    }
});