# Generated by Django 6.0.3 on 2026-04-05 04:28

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='travels.booking'),
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travels.baseservice'),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PROVIDER', 'provider'), ('CUSTOMER', 'customer')], default='CUSTOMER', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('customer', 'service')},
        ),
    ]
