# Generated by Django 6.0.3 on 2026-04-05 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_booking_quantity_hotelservice_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baseservice',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='amenities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('MOMO', 'MoMo'), ('ZALOPAY', 'ZaloPay')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transportservice',
            name='vehicle_type',
            field=models.CharField(choices=[('FLIGHT', 'Máy bay'), ('BUS', 'Xe khách'), ('SHIP', 'Tàu')], default='BUS', max_length=15),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='seat_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
