# Generated by Django 6.0.3 on 2026-04-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_payment_transaction_id_alter_payment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang xử lý'), ('COMPLETED', 'Đã thành công'), ('FAILED', 'Đã thất bại')], default='PENDING', max_length=20),
        ),
    ]
