# Generated by Django 6.0.3 on 2026-04-22 02:02

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='checkin_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='checkout_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='policy',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='star_rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='itinerary',
            field=ckeditor.fields.RichTextField(help_text='Lịch trình chi tiết', null=True),
        ),
        migrations.AddField(
            model_name='tourservice',
            name='meeting_point',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportservice',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transportservice',
            name='from_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportservice',
            name='to_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='comboservice',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='comboservice',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='comboservice',
            name='transport',
        ),
        migrations.AddField(
            model_name='comboservice',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='travels.hotelservice'),
        ),
        migrations.AddField(
            model_name='comboservice',
            name='tour',
            field=models.ManyToManyField(blank=True, to='travels.tourservice'),
        ),
        migrations.AddField(
            model_name='comboservice',
            name='transport',
            field=models.ManyToManyField(blank=True, to='travels.transportservice'),
        ),
    ]
