# Generated by Django 6.0.3 on 2026-04-22 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_hotelservice_checkin_time_hotelservice_checkout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Ngày nhận phòng/Ngày khởi hành', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
