# Generated by Django 6.0.3 on 2026-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_booking_adult_count_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservice',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
