# Generated by Django 6.0.3 on 2026-04-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='owner_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='reply_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
