# Generated by Django 6.0.3 on 2026-04-27 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_rating_owner_reply_rating_reply_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('SCAM', 'Dấu hiệu lừa đảo'), ('INCORRECT_INFO', 'Thông tin không chính xác'), ('BAD_SERVICE', 'Chất lượng dịch vụ kém'), ('OTHER', 'Lý do khác')], default='OTHER', max_length=50)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('RESOLVED', 'Đã xử lý'), ('DISMISSED', 'Đã bác bỏ')], default='PENDING', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='travels.baseservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
